### PR TITLE
add 'org.codehaus.groovy.' to struts.excludedPackageNames

### PR DESCRIPTION
**Pull request by sullis**

### CODE REVIEW

**Comment by sullis** [comment]
@lukaszlenart

**Comment by yasserzamani** [comment]
But Struts hasn't any dependency to `org.codehaus.groovy`.

**Comment by sullis** [comment]
Motivation:  **Secure By Default** philosophy

https://en.wikipedia.org/wiki/Secure_by_default

"Security by default, in software, means that the default configuration settings are the most secure settings possible"

**Comment by lukaszlenart** [comment]
We won't block the whole world and I agree with Yasser in this case. This is also developer/devops responsibility to properly exclude potentially vulnerable classes.

**Pull request closed without merging**
