### PR TITLE
WW-5197 Adds support for java.sql.Date

### PR DESCRIPTION
**Pull request by tobiasstadler**
Fixes [WW-5197](https://issues.apache.org/jira/browse/WW-5197)

### CODE REVIEW

**Comment by tobiasstadler** [comment]
> Nice, wouldn't you mind adding a test case to cover `java.sql.Date`?

Done

**Comment by lukaszlenart** [comment]
👏

**Comment by tobiasstadler** [comment]
@lukaszlenart Is there anything missing from my side?

**Comment by lukaszlenart** [comment]
LGTM 👍

**Pull request merged**
