### PR TITLE
WW-4909: Renames a constant and adds a test

### PR DESCRIPTION
**Pull request by lukaszlenart**
Implements [WW-4909](https://issues.apache.org/jira/browse/WW-4909)

### CODE REVIEW

**Comment by lukaszlenart** [comment]
😭

**Comment by lukaszlenart** [comment]
I will add more tests

**Comment by lukaszlenart** [comment]
lel ... I have read `increased` as `decreased` :P

**Comment by lukaszlenart** [comment]
@apache/struts-committers ready for review, please also check https://github.com/apache/struts-site/pull/97

**Comment by sdutry** [comment]
👍 LGTM

**Comment by yasserzamani** [comment]
> lel ... I have read increased as decreased :P

You have read right. I don't know why but coverall seems comments as `decreased` then edits it! My received email below proofs this:

> Coverage decreased (-0.01%) to 46.406% when pulling 355e4b5 on lukaszlenart:limitable-extendable into 9bf89f8 on apache:master.

**Comment by yasserzamani** [comment]
> 👍 LGTM

Same here 👍

**Comment by lukaszlenart** [comment]
osm! can someone hit the button?

**Pull request merged**
