### PR TITLE
Minor Formatting changes

### PR DESCRIPTION
**Pull request by sdutry**
- made some minor formatting changes concerning:
  - mixed tabs and spaces
  - add curly brackets around single line conditional statements
- added some missing ´@Override´ annotations

### CODE REVIEW

**Comment by lukaszlenart** [comment]
Looks good to me but it would be nice if you could increase coverage to satisfy Coveralls :)

**Comment by sdutry** [comment]
> if you could increase coverage to satisfy Coveralls

I'll look into it.
It's a bit annoying that it counts the lines with only a closing bracket => decreased coverage.

**Comment by sdutry** [comment]
@lukaszlenart 
slowly getting there
> Coverage decreased (-0.01%) to 46.285%

to 

> Coverage decreased (-0.007%) to 46.289%

**Comment by lukaszlenart** [comment]
💯

**Comment by lukaszlenart** [comment]
@sdutry ready to be merged?

**Comment by sdutry** [comment]
@lukaszlenart 
> ready to be merged?

I think so.
Unless you have other changes you want to see done?

Maybe the following piece of comment should be removed?
```java
 /**
  *		  
  * @version $Date$ $Id$
  */		 
 public class UIBeanTest extends StrutsInternalTestCase {
```

**Comment by lukaszlenart** [comment]
Yes, please do, those are some leftovers from Subversion - not in use anymore

**Comment by lukaszlenart** [comment]
nice, LGTM 👍

**Pull request merged**
