### PR TITLE
WW-3952: Credit card validator

### PR DESCRIPTION
**Pull request by lukaszlenart**
Implements a credit card validator
[WW-3952](https://issues.apache.org/jira/browse/WW-3952)

### CODE REVIEW

**Comment by lukaszlenart** [comment]
This is ready for review

**Comment by cnenning** [comment]
I hope the regex is stable 😉

**Comment by lukaszlenart** [comment]
> I hope the regex is stable 

What do you mean by that? I have used this http://www.regular-expressions.info/creditcard.html

**Comment by cnenning** [comment]
How often do credit card companies change their number-patterns in a way that the regex needs to be updated? 'guess it is rare enough.

**Comment by lukaszlenart** [comment]
Good question... I have used those random card numbers in tests and looks ok (but we will see) https://www.paypalobjects.com/en_US/vhelp/paypalmanager_help/credit_card_numbers.htm

**Comment by cnenning** [comment]
If patterns change users have another reason to upgrade to latest struts 😆

**Comment by gregh3269** [comment]
Last time I did some credit card validation, I needed to use a java script version as the payment process obscured the field names by not having the "name" attribute (so it was not obvious when these were sent over https) and I was unable to do server side validation.

**Pull request merged**
