### PR TITLE
introduce integration tests with minimum needed changes

### PR DESCRIPTION
**Pull request by yasserzamani**
- upgrades jwebunit to latest available version
- downgrades to jquery 1.8.2 and bootstrap 2.0.3 for jwebunit compatibility

### CODE REVIEW

**Comment by aleksandr-m** [comment]
Why downgrade jQuery and Bootstrap?

**Comment by aleksandr-m** [comment]
How about using HtmlUnit directly or some other testing framework. jQuery 1.8.2 probably is full of security vulnerabilities. Using ancient dependencies because of web testing, I would say: no go.

**Comment by lukaszlenart** [comment]
As I see you did it :)

**Comment by aleksandr-m** [comment]
Do integration tests work now?

> currently it contains them but with 0 as coverage

Does this means no? What benefit this PR brings then?

Why not to extend this PR with more up to date web testing framework?

We should really upgrade jQuery and Bootstrap to latest versions.

**Comment by aleksandr-m** [comment]
I've managed to convert most of the tests using `HtmlUnit`. Just a few tricky tests left. Stay tuned... :)

**Comment by yasserzamani** [comment]
Wow! you did it, those warning about css also vanished now  🥇 👏 thanks a lot! I'll squash and merge them :)

**Comment by yasserzamani** [comment]
I'm sorry @aleksandr-m , I squashed to avoid spamming git log and history but GitHub has merged your works with my name :( excuse me as I didn't know this.

**Comment by aleksandr-m** [comment]
@yasserzamani Squash tends to do that. :) Don't sweat it. Though personally I would merge this particular PR instead of squashing it. Besides few typo fixing commits it has clear logically separated commits.

**Pull request merged**
