### PR TITLE
Pimp my struts

### PR DESCRIPTION
**Pull request by lukaszlenart**
Some small tweaks to be better visible via GitHub

Coverage report is available here
https://coveralls.io/github/apache/struts
[Coverage Status](https://coveralls.io/github/apache/struts?branch=pimp-my-struts)

### CODE REVIEW

**Comment by lukaszlenart** [comment]
@apache/struts-committers I think this is ready to be merged

**Comment by cnenning** [comment]
I like it 👍

**Comment by yasserzamani** [comment]
It's great 👍 just coverall comment here is somehow different than [here](https://github.com/apache/commons-lang/pull/261#issuecomment-289265370).

**Comment by lukaszlenart** [comment]
because there is nothing to compare to

**Comment by yasserzamani** [comment]
Oh sorry, I failed to catch that :( you're right.

Thanks for your works 👍

**Comment by yasserzamani** [comment]
I compared this PR changes with Apache Commons Lang and it seems ok to go :)

**Comment by lukaszlenart** [comment]
@apache/struts-committers I have added two more plugins to discover outdated dependencies

**Comment by lukaszlenart** [comment]
No complains so LGTM :)

**Pull request merged**
