### PR TITLE
Better logging message (for WW-4954)

### PR DESCRIPTION
**Pull request by aleksandr-m**

### CODE REVIEW

**Comment by lukaszlenart** [comment]
What about messages in other cases?

**Comment by lukaszlenart** [comment]
I've kicked Jenkins to rebuild this and everything went smoothly, LGTM 👍

**Comment by lukaszlenart** [comment]
Do you plan to cherry-pick this to 2.3 or 2.5?

**Comment by aleksandr-m** [comment]
Cherry picked to 2.5 and opened PR to 2.3

**Pull request merged**
