### PR TITLE
WW-4634 for support-2-3

### PR DESCRIPTION
**Pull request by victorsosa**
Cherry-pick PR for support-2-3

### CODE REVIEW

**Comment by lukaszlenart** [comment]
As far I understand the issue was in 2.5 only, 2.3 works as expected.

**Comment by victorsosa** [comment]
But it is using the parameter align instead of a css class. the align parameter is deprecated in html 5.

**Comment by lukaszlenart** [comment]
That's why people should migrate to 2.5 ;-) I think we can ask reported if he wants the same in 2.3

**Comment by victorsosa** [comment]
OK

**Comment by victorsosa** [comment]
PR remove, it wasn't requested

**Pull request closed without merging**
