### PR TITLE
WW-2411 Add a maxlength attribute to the textarea tag 

### PR DESCRIPTION
**Pull request by kerttup**
Maxlength attribute added to textarea tag

### CODE REVIEW

**Comment by lukaszlenart** [comment]
You must also modify [`template/simple/textarea.ftl`](https://github.com/apache/struts/blob/master/core/src/main/resources/template/simple/textarea.ftl#L21-L47), add something like this:
```
<#if parameters. maxlength?has_content>
 maxlength ="${parameters. maxlength}"<#rt/>
</#if>
```

**Comment by lukaszlenart** [comment]
Also would you mind adding `minlength`?
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea#attributes

**Comment by kerttup** [comment]
Modified textarea.ftl and added also minlength attribute.

**Review by lukaszlenart — APPROVED** [review]
Nicely done :) LGTM 👍

**Comment by lukaszlenart** [comment]
@kerttup do you plan port these changes into 2.5.x branch?

**Comment by kerttup** [comment]
Hi @lukaszlenart, what do you mean with plan port? This was my first pull request so I am new to this and dont know the practices yet.

**Comment by lukaszlenart** [comment]
We are currently developing two versions of Struts
- `master` branch represents incoming [Struts 2.6](https://issues.apache.org/jira/projects/WW/versions/12340222)
- `struts-2-5-x` branch is used to maintain current [Struts 2.5.x](https://issues.apache.org/jira/projects/WW/versions/12349611)

You addressed your fix just against the `master` branch which means it will be included in Struts 2.6 - this is fine if you can wait on that version to be released probably in a few months. If you would like to see your fix early, you must _port_ it to `struts-2-5-x` branch by cherry-picking the changes and opening a new PR against `struts-2-5-x` branch.

**Comment by kerttup** [comment]
Thanks for the clarification. I think this can wait until the next version.

**Pull request merged**
