### PR TITLE
WW-4910 Align OptGroup with Select

### PR DESCRIPTION
**Pull request by quaff**
1. allow set freemarker sequence or hash as list
2. if list is a List, use 'top' as listKey and listValue

Implements [WW-4910](https://issues.apache.org/jira/browse/WW-4910)

### CODE REVIEW

**Comment by lukaszlenart** [comment]
It would be good to add a test to cover this case.

**Comment by quaff** [comment]
Updated with test case.

**Comment by yasserzamani** [comment]
@quaff , thanks a lot. I also discovered a few issues during reviewing which I fixed in three pushes into your branch :)

@apache/struts-committers , LGTM , However, I also pushed some changes, so, Once reviewed, I think you can squash and merge it.

**Comment by lukaszlenart** [comment]
2.5.16 is out so we can start working on 2.6 :)

**Comment by lukaszlenart** [comment]
👍

**Pull request merged**
