### PR TITLE
WW-5124 - Proposed fix for Struts JSP tag behaviour with tag pooling (re-target to 2.6.x)

### PR DESCRIPTION
**Pull request by JCgH4164838Gh792C124B5**
Hello Apache Struts Team.

This PR is a re-target of PR #489 aiming the equivalent changes to the 2.6.x main branch (hopefully the cherry-picks and subsequent cleanup are OK).  Please see the original PR for background and discussion details.

This PR attempts to add logic to call cleanup in the `release()` method for the Tag handler as well, but otherwise should be equivalent to the original PR for 2.5.x.

There may be a better strategy/design to consider instead, but at least it provides a starting point.  Please let me know if anyone can see a cleaner solution.

### CODE REVIEW

**Comment by JCgH4164838Gh792C124B5** [comment]
The latest update attempts to improve test coverage a bit (in response to the coveralls report), but to do so it also had to merge recent mainline changes, due to conflicts.

During this activity, it was discovered that the `DateTextFieldTag` may not be functional anymore.  If that is true, then maybe it should be corrected or dropped at a later date.

**Review by lukaszlenart — COMMENTED** [review]
👏  👏  👏  a huge amount of work, LGTM 💯 
I will give others time to review these changes before merging

**Comment by yasserzamani** [comment]
Thanks a lot @JCgH4164838Gh792C124B5 LGTM :+1: as well. And apologize in advance that my merge has caused a small conflict here, sorry didn't know.

**Comment by lukaszlenart** [comment]
@JCgH4164838Gh792C124B5 conflictes have appeared after merging Yasser's changes, could you update your branch? Thanks a lot! :)

**Comment by JCgH4164838Gh792C124B5** [comment]
Hi @lukaszlenart and @yasserzamani .  Thanks for the heads-up about the conflicts.  I will attempt to resolve the conflicts locally (hopefully soon), and push a new commit with any changes that are needed.

**Comment by JCgH4164838Gh792C124B5** [comment]
Hi.  The branch has been updated to resolve the merge conflicts.  If anything looks wrong, just let me know.

**Comment by yasserzamani** [comment]
thank you @JCgH4164838Gh792C124B5 !

**Pull request merged**
