### PR TITLE
WW-4623 Multiple tiles.xml in web.xml

### PR DESCRIPTION
**Pull request by victorsosa**
WW-4623, WW-4624

Multiple tiles.xml in web.xml

Now it will load all the "**/tiles*.xml" below WEB-INF and also load individual files using the <context-param>

### CODE REVIEW

**Comment by aleksandr-m** [comment]
Not working for 2.3.x and doubt it will work in 2.5. Take a look at `ResourceFinder`.

Please try to write a unit tests along with code changes, and if it is somehow complicated then at least test things manually.

**Comment by victorsosa** [comment]
Thanks for you help, Aleksandr; can you please post the stack trace of that? So I can look with more info into ResourceFinder

**Comment by aleksandr-m** [comment]
In 2.3.28 `StrutsWildcardServletTilesApplicationContext` produces something like that:

> org.apache.struts2.tiles.StrutsTilesListener - Starting Struts Tiles 2 integration ...
> org.apache.struts2.tiles.StrutsTilesInitializer - Initializing Tiles wildcard support ...
> org.apache.struts2.tiles.StrutsWildcardServletTilesApplicationContext:
> 
> url= file:/path/to/webapps/app/img/
> url= file:/path/to/webapps/app/js/
> url= file:/path/to/webapps/app/META-INF/
> url= file:/path/to/webapps/app/index.jsp
> url= file:/path/to/webapps/app/WEB-INF/
> url= file:/path/to/webapps/app/css/
> url= file:/path/to/webapps/app/favicon.ico

And `ResourceFinder#getResourcesMap` won't look into sub-folders, meaning that `**/tiles` pattern is irrelevant in such case.

**Comment by victorsosa** [comment]
Code implement by Lukas already

**Pull request closed without merging**
