### PR TITLE
Update Struts 2.6 to the latest OGNL 3.2.x version available.

### PR DESCRIPTION
**Pull request by JCgH4164838Gh792C124B5**
Update Struts 2.6 to the latest OGNL 3.2.x version available.

### CODE REVIEW

**Comment by lukaszlenart** [comment]
Maybe we should postpone this PR till I will release a new OGNL 3.2.x version?

**Comment by lukaszlenart** [comment]
Up to you, 3.2.10 is already out
https://search.maven.org/artifact/ognl/ognl/3.2.10/jar

**Comment by JCgH4164838Gh792C124B5** [comment]
Hello again.

I have amended the last commit to use OGNL 3.2.10.  It built successfully locally (no errors) using JDK 7u79, so it looks promising.  :)

**Comment by lukaszlenart** [comment]
Osm! LGTM 👍

**Pull request merged**
