### PR TITLE
Update maven wrapper to 3.8.6

### PR DESCRIPTION
**Pull request by sepe81**

### CODE REVIEW

**Comment by sepe81** [comment]
Hello @lukaszlenart - the Travis CI build fails b/c of `Error: JAVA_HOME is not defined correctly.`. Do you know why this happens occasionally?

**Comment by sepe81** [comment]
@lukaszlenart One more question. Do you see any value in keeping the separate oraclejdk9 build? Java 9 is EOL and IMHO keeping Java 8, Java 11 and maybe adding Java 17 LTS would be helpful. (Should I create a Jira issue for this?)

**Comment by lukaszlenart** [comment]
> Do you see any value in keeping the separate oraclejdk9 build? Java 9 is EOL and IMHO keeping Java 8, Java 11 and maybe adding Java 17 LTS would be helpful. (Should I create a Jira issue for this?)

Nope, adding Java 17 has more sense (ticket is not needed), thanks!

**Comment by lukaszlenart** [comment]
LGTM 👍

**Pull request merged**
