### PR TITLE
WW-5350 Implement OGNL Allowlist capability

### PR DESCRIPTION
**Pull request by kusalk**
WW-5350
--
Implementation for strict OGNL allowlist feature. It is up to the application to determine which classes/packages need to be allowlisted. The exclusion list will still take precedence (classes on the exclusion list cannot be allowlisted).

I hope to clean this implementation up and both `OgnlUtil` and `SecurityMemberAccess` up as part of WW-5343.

### CODE REVIEW

**Comment by lukaszlenart** [comment]
It would be good to document this new future to more visible to the users. Could you also add a section about this new _allow list_ [here](https://struts.apache.org/security/#internal-security-mechanism)?

**Review by lukaszlenart — APPROVED** [review]

**Comment by kusalk** [comment]
@lukaszlenart Yep I'll add something about the OgnlGuard too

**Comment by kusalk** [comment]
@lukaszlenart Going to merge this - but I haven't forgotten about the documentation - I will throw up a PR covering all new capabilities as soon as I've finished #791 :)

**Review by Gowza68 — APPROVED** [review]

**Comment by Gowza68** [comment]
- [ ]

**Comment by quansat775-ux** [comment]
#1511

**Comment by quansat775-ux** [comment]
#1509

**Review by asrar-mared — COMMENTED** [review]
الملفات المتغيره

**Review by ksealmalaysia41-lang — APPROVED** [review]

**Review by Ivanreyes9 — APPROVED** [review]

**Review by ntorrento08-creator — APPROVED** [review]
reparing copiloto to be un my side to not cuestión my judgemente

**Comment by ksealmalaysia41-lang** [comment]
Yeah I didn't again.sorry guys Reward on me.

**Pull request merged**
