### PR TITLE
ConversionErrorInterceptor to extend MethodFilterIntercept

### PR DESCRIPTION
**Pull request by gregh3269**
See WW-4676

Cheers

### CODE REVIEW

**Comment by lukaszlenart** [comment]
Some tests failed https://builds.apache.org/job/Struts-JDK7-pull-request/209/org.apache.struts$struts2-core/testReport/

**Comment by gregh3269** [comment]
OK, looks like it needs a doIntercept(..) rather than in Intercept().

**Comment by lukaszlenart** [comment]
Still two tests are failing ... I think it would be better to setup `excludeMethods`/`includeMethods` in test and call`intercept()`

**Comment by gregh3269** [comment]
Revert "WW-4628: proper decoding of parameters in query-string"

Sorry, this was a bad by not really understanding git and git making
automatic commits, it should not have modified any other code.  Especially not the revert.

How would this be fixed now?

**Comment by cnenning** [comment]
> How would this be fixed now?

I fixed it already just by running `git cherry-pick`. (there is a jira comment about it)

I feared that monstrous issue ([WW-4628](https://issues.apache.org/jira/browse/WW-4628)) would get another round of discussion and was relieved that it was just an accident :wink:

**Comment by gregh3269** [comment]
Great thanks!

**Comment by lukaszlenart** [comment]
@gregh3269 the best options is to not perform those reverse merges (like b6be359) if there is no conflicts.

**Pull request merged**
