### PR TITLE
WW-3945 Json default encoding UTF-8

### PR DESCRIPTION
**Pull request by victorsosa**
Now the Json encoding by default is utf-8

### CODE REVIEW

**Comment by lukaszlenart** [comment]
Conflicts :(

**Comment by victorsosa** [comment]
Yea, My bad; Let me fix it

**Comment by victorsosa** [comment]
Done, check Jenkins; it seems to be blocked

**Comment by lukaszlenart** [comment]
Yes, there is few other builds in pipeline ;-)

**Comment by victorsosa** [comment]
:+1:

**Pull request merged**
