### PR TITLE
WW-4356  Implement new Sitemesh plugin based on Sitemesh3 - Sitemesh update 

### PR DESCRIPTION
**Pull request by victorsosa**
WW-4356 Implement new Sitemesh plugin based on Sitemesh3

sitemesh update

### CODE REVIEW

**Comment by lukaszlenart** [comment]
I thought you did also some code cleanups/improvements :(

**Comment by victorsosa** [comment]
I did'nt because I did not get any compile error here, weird; But I am working on it so the code compile

**Comment by lukaszlenart** [comment]
ok, I just wanted to throw away some code, maybe some duplicates, etc. but I'm not a Sitemesh expert :)

**Comment by victorsosa** [comment]
for example VelocityPageFilter and FreemarkerPageFilter aren't used, right? and can be deleted

**Comment by victorsosa** [comment]
Closing this PR; I didn't get any support from this Sitemesh community; this project seems to be dead; there is not point on upgrade it.

**Pull request closed without merging**
