### PR TITLE
WW-4636 File upload error message always in default language

### PR DESCRIPTION
**Pull request by victorsosa**
File upload error message always in default English language.

Content negotiation is a mechanism defined in the HTTP specification is
used in the code; now using the 'Accept-Language: us' in the request the language is choose.

The bug was that it was always using the English language for the
message.

### CODE REVIEW

**Comment by aleksandr-m** [comment]
First of all, there is [some chance](https://github.com/apache/struts/blob/master/core/src/main/java/org/apache/struts2/dispatcher/multipart/JakartaMultiPartRequest.java#L71) that `defaultLocale` isn't set to English.

Can we get locale from the action context instead of request?

**Comment by victorsosa** [comment]
@aleksandr-m  It is set to English in here: https://github.com/apache/struts/blob/master/core/src/main/java/org/apache/struts2/dispatcher/multipart/JakartaMultiPartRequest.java#L62

get locale from the action context instead of request?... I will check that

**Comment by aleksandr-m** [comment]
@victorsosa, @lukaszlenart Please close this one. WW-4636 is fixed in https://github.com/apache/struts/pull/113.

**Comment by victorsosa** [comment]
done

**Pull request closed without merging**
