### PR TITLE
WW-4805 Ports some of PR #142 changes to branch support-2-3

### PR DESCRIPTION
**Pull request by yasserzamani**
Ports only security related changes of #142 to branch support-2-3

### CODE REVIEW

**Comment by lukaszlenart** [comment]
I'm not able to merge this PR as it also contains some changes from the `master` branch - I have no idea how does it happen, maybe some GitHub PR's magic :\ I will try to cherry-pick this.

**Comment by lukaszlenart** [comment]
Did you cherry-pick changes from your original branch? As this is the only option to port changes merged to the `master` branch back to the `support-2-3` branch.

**Comment by yasserzamani** [comment]
😕 When I was in my branch `master`, I checked out my `support-2-3`. Then I pulled apache `support-2-3` then pushed into my `support-2-3`. I confirmed via github that my `support-2-3` and apache `support-2-3` are even ( at [here](https://github.com/yasserzamani/struts/tree/support-2-3) ). Then I checked out my `support-2-3` as a new branch named `support-2-3-WW-4805`. Finally I made my changes on it, then commit and push it as a new branch into my github, then create this PR against apache `support-2-3`.

At github all things seems good!

**Comment by yasserzamani** [comment]
Forgot to say I did not any cherry-pick :)

**Comment by lukaszlenart** [comment]
So you have made all the changes by hand, not be merging in another branch, right?

**Comment by yasserzamani** [comment]
Yes. All done by coping just raw texts then delete or edit them. I was aware that merging will mix things up and is confusing so I avoided.

Do you have trouble withe mirrored github or apache's original repository?

**Comment by lukaszlenart** [comment]
After checking out your PR locally I cannot build it on JDK6 (Struts 2.3.x must be built on JDK 6)

**Comment by yasserzamani** [comment]
Thanks! I did not try JDK6. Please let me check.

**Comment by yasserzamani** [comment]
OK, I tried JDK6 which firstly has failed with heap out of memory message at `Running org.apache.struts2.components.UIComponentTest`. But when I replaced JDK with a 64bit version and `-Xmx2048m`, then `mvn -DskipAssembly=true install` exited successfully with code 0. Used Maven version was 3.2.5, latest JDK6 compatible maven.

Do you get same error message as me (i.e. heap out of memory) when you use `mvn -X`?

**Comment by lukaszlenart** [comment]
Nope, I'm getting compilation errors:
```
[ERROR] chainHistory = new LinkedList<>();
```

which means when I fetch your PR it was merged against the `master` branch instead of the `support-2-3` - I need to figure out what's going on.

**Comment by yasserzamani** [comment]
@lukaszlenart , it seems it was occurred just on your local PC during git fetch and there is not any issue with github or original apache repositories. Please revert your local changes and try check out instance of fetch. I remember the fetch does a merge too!

**Comment by lukaszlenart** [comment]
Nope, I mean PRs are a GitHub specific feature, and looks like PR is always merged with the `master` branch so checking out the PR isn't an option to test non-`master` PRs ;-)

https://help.github.com/articles/checking-out-pull-requests-locally/

For reference:
I had to add your repository as an another `remote` and fetch your branch directly and merge it into the `support-2-3` branch to workaround the above problem.

**Pull request merged**
