### PR TITLE
WW-4578: Multidimensional validation

### PR DESCRIPTION
**Pull request by lukaszlenart**
This PR adds support for validation of Collections in field validators

Resolves [WW-4578](https://issues.apache.org/jira/browse/WW-4578)

### CODE REVIEW

**Comment by cnenning** [comment]
IMO these 4 could be considered, too:

- `DoubleRangeFieldValidator`
- `URLValidator`
- `RequiredStringValidator`
- `StringLengthFieldValidator`

**Comment by lukaszlenart** [comment]
- ~`DoubleRangeFieldValidator`~
- `URLValidator`
- `RequiredStringValidator`
- `StringLengthFieldValidator`

**Comment by lukaszlenart** [comment]
- ~`DoubleRangeFieldValidator`~
- `URLValidator`
- ~`RequiredStringValidator`~
- `StringLengthFieldValidator`

**Comment by lukaszlenart** [comment]
- ~`DoubleRangeFieldValidator`~
- `URLValidator`
- ~`RequiredStringValidator`~
- ~`StringLengthFieldValidator`~

**Comment by lukaszlenart** [comment]
- ~`DoubleRangeFieldValidator`~
- ~`URLValidator`~
- ~`RequiredStringValidator`~
- ~`StringLengthFieldValidator`~

**Comment by wolpi** [comment]
+1 for merging 😆

**Pull request merged**
