### PR TITLE
WW-4762: Default provider

### PR DESCRIPTION
**Pull request by lukaszlenart**
Implements a default text provider which only operates on defined default bundles and those provided via `struts.custom.i18n.resources`

Implements [WW-4762](https://issues.apache.org/jira/browse/WW-4762)

### CODE REVIEW

**Comment by lukaszlenart** [comment]
This is ready to test, to test the new bean you must specify the following constant in `struts.xml`

```xml
<constant name="struts.localizedTextProvider" value="default-only" />
```

now you can play with `struts.custom.i18n.resources` to define additional resource bundles.

**Comment by lukaszlenart** [comment]
Any objections to merge this PR?

**Comment by gregh3269** [comment]
I can re-test it when merged.

**Comment by lukaszlenart** [comment]
Please see docs, I have renamed the constant and the class
https://cwiki.apache.org/confluence/display/WW/Localization#Localization-Usingonlyglobalbundles

**Pull request merged**
