### PR TITLE
WW-5033 - Update to latest versions for some Struts 2.5.x dependencies:

### PR DESCRIPTION
**Pull request by JCgH4164838Gh792C124B5**
WW-5033 - Update to latest versions for some Struts 2.5.x dependencies:
- ASM 7 -> 7.1
- OGNL 3.1.23 -> 3.1.24
- Spring 4.3.20.RELEASE -> 4.3.24.RELEASE

### CODE REVIEW

**Comment by JCgH4164838Gh792C124B5** [comment]
Hello Apache Struts Devs.

The regression built successfully locally (JDK7), and for JDK 11 via Travis.  There doesn't appear to be any issue with the dependency version changes based on those results, but someone else should confirm.

```
The Travis CI job is still failing for JDK 7, 8 and 9 with errors like:
/install-jdk" --feature "7" --license "GPL" --cacerts" failed and exited with 3 during .
/install-jdk" --feature "8" --license "BCL"" failed and exited with 3 during .
/install-jdk" --feature "9" --license "BCL"" failed and exited with 8 during .
Your build has been stopped.

```
For JDK 7 and 8 the Travis build complains with: "Expected feature release number in range of 9 to 14, but got: 7 "(or 8).  Looks like it isn't attempting to retrieve/install either JDK 7 or 8 as a result.

**Looks like others have reported similar Travis CI issues recently too** (https://travis-ci.community/t/error-installing-oraclejdk8-expected-feature-release-number-in-range-of-9-to-14-but-got-8/3766).

For JDK 9 it looks like the download from OTN may simply be failing - changes in access rules ?

**Comment by yasserzamani** [comment]
Hi,

I wasn't notified for OGNL 3.1.24 release and it doesn't have all what I had planned to add. I had planned to replace `A = B.getDeclaredXXX` with `try{A = B.getDeclaredXXX}catch(SecurityException){A = B.getXXX}` which minimizes Struts test failures under a SecurityManager (e.g. OgnlSecurityManager).

Generally once I adapted Struts with OgnlSecurityManager having minimum test failures, we can release next OGNL and update Struts to use it.

Kind regards.

**Comment by lukaszlenart** [comment]
I'm catching up on outstanding issues, so I assume I must merge all the PRs targeting OGNL 3.1.x, release a new version and then switch back to this issue, right?

**Comment by yasserzamani** [comment]
No. @JCgH4164838Gh792C124B5 reverted OGNL version at last commit. Now this PR is only about ASM and Spring versions update. I wish we could fix Travis issue on this PR to see if it passes all tests,  albeit I'm not sure if it's a good idea to do these version updates in 2.5 as we were going to set it to maintenance version.

**Comment by lukaszlenart** [comment]
Thanks for the clarification! And to fix Travis build, this change 8f96dca4dc2ea0bbc7e011d7e9969c60d786a3ad must be cherry-picked here.

**Comment by yasserzamani** [comment]
Thanks! LGTM 👍

**Comment by lukaszlenart** [comment]
👏

**Pull request merged**
