### PR TITLE
WW-4899: upgrade Spring

### PR DESCRIPTION
**Pull request by lukaszlenart**
Upgrades Spring to version 4.3.13

Refers [WW-4899](https://issues.apache.org/jira/browse/WW-4899)

### CODE REVIEW

**Comment by yasserzamani** [comment]
Thank you! LGTM 👍 What do you feel to deliver this with 2.5.15 too?

**Comment by lukaszlenart** [comment]
This can be a major change, switching from Spring 4.1 to 4.3 can break users' apps. I would wait till 2.6.

**Comment by aleksandr-m** [comment]
It should be rather safe. Spring dependencies are optional in core and for those who use spring in their projects they've probably overridden it already.

**Comment by lukaszlenart** [comment]
Ok, let's merge it, who want to pull the trigger?

**Comment by lukaszlenart** [comment]
Ok @yasserzamani & @aleksandr-m you have convinced me, please merge this puppy :)

**Pull request merged**
