### PR TITLE
 WW-4622 [struts2-tiles-plugin] [StrutsWildcardServletTilesApplicationContext] getRealPath 

### PR DESCRIPTION
**Pull request by victorsosa**
[struts2-tiles-plugin] [2.3.28] [StrutsWildcardServletTilesApplicationContext] getRealPath

protect the struts API by avoiding the NPE calling ServletContext.getRealPath()

### CODE REVIEW

**Comment by victorsosa** [comment]
Travis is no compiling correctly because is using OpenJDK 7 instead of Java JDK 7

**Comment by aleksandr-m** [comment]
Resources still need to be loaded, NPE check is not enough.

BTW recently portlet-webapp test fails in my environment too (Oracle JDK).

**Comment by victorsosa** [comment]
This is the stack trace of the recently portlet-webapp test fails 

```
2016-04-03 15:47:03,142 ERROR [btpool0-1] dispatcher.Jsr168Dispatcher (Jsr168Dispatcher.java:487) - Could not execute action

javax.portlet.PortletException: org.apache.jasper.JasperException: /WEB-INF/view/index.jsp(1,42) PWC6117: File "/struts-tags" not found

	at org.apache.pluto.internal.impl.PortletRequestDispatcherImpl.include(PortletRequestDispatcherImpl.java:115) ~[pluto-container-1.1.6.jar:?]

	at org.apache.struts2.portlet.result.PortletResultHelperJSR168.include(PortletResultHelperJSR168.java:51) ~[classes/:?]

	at org.apache.struts2.portlet.result.PortletResult.executeMimeResult(PortletResult.java:227) ~[classes/:?]
```

**Comment by aleksandr-m** [comment]
This alone is not enough to solve [WW-4622](https://issues.apache.org/jira/browse/WW-4622). The `ResourceFinder` won't handle that case.

**Comment by lukaszlenart** [comment]
You can ignore Travis for now - I have enabled it experimentally but those tests must be fixed at some point :)

**Comment by aleksandr-m** [comment]
And this will break working stuff also.

**Comment by victorsosa** [comment]
Close this PR; the code was implemented by aleksandr-m

**Pull request closed without merging**
