### PR TITLE
[WW-5115] Reduce logging of ignored DMI params

### PR DESCRIPTION
**Pull request by lukaszlenart**
@gregh3269 what about such simple solution?

Resolves [WW-5115](https://issues.apache.org/jira/browse/WW-5115)

### CODE REVIEW

**Comment by yasserzamani** [comment]
I think the reported issue is invalid. please refer to my comment in corresponding jira ticket

**Comment by lukaszlenart** [comment]
Ok, closing this PR

**Comment by lukaszlenart** [comment]
Reopening as requested by @gregh3269

**Comment by lukaszlenart** [comment]
Changes have been cherry-picked into #526

**Pull request closed without merging**
