### PR TITLE
WW-4849: Initializable interface

### PR DESCRIPTION
**Pull request by lukaszlenart**
Fixes [WW-4849](https://issues.apache.org/jira/browse/WW-4849)

### CODE REVIEW

**Comment by aleksandr-m** [comment]
Works in my simple test project. I'll try to test it in more complex project tomorrow.

**Comment by gstein** [comment]
Closing and re-opening, per @lukaszlenart.

**Comment by aleksandr-m** [comment]
@lukaszlenart Seems to be working. Good job!

**Comment by lukaszlenart** [comment]
@aleksandr-m great, I will give few more days others to post a comment :)

**Comment by yasserzamani** [comment]
Nice work! I added some logs and compared S2.5.12 with this PR:

S2.5.12 vs PR168

**Comment by lukaszlenart** [comment]
Thanks a lot, I think we can merge this in and start thinking about another release to fill the gap :)

**Comment by lukaszlenart** [comment]
Closes #165

**Pull request merged**
