### PR TITLE
sync up execution ids with top-level Apache pom, otherwise the sources are deployed twice during release

### PR DESCRIPTION
**Pull request by pbruski**

### CODE REVIEW

**Comment by lukaszlenart** [comment]
Please create an issue in JIRA and link here - we use this to prepare version notes.

**Comment by lukaszlenart** [comment]
Is this the same PR as #100? I see the same changes

**Comment by pbruski** [comment]
I've accidentally mixed up two PRs in #100 .
The issue is: https://issues.apache.org/jira/browse/WW-4653

**Comment by lukaszlenart** [comment]
Szl@g! I have merged the wrong PR :\

**Pull request merged**
