### PR TITLE
fix WW-5165 Update spring to 5.3.x b/c 4.3.x is EOL

### PR DESCRIPTION
**Pull request by victorsosa**
Refs [WW-5165](https://issues.apache.org/jira/browse/WW-5165)

### CODE REVIEW

**Comment by lukaszlenart** [comment]
Is it ok to merge this PR? //cc: @sepe81

**Comment by victorsosa** [comment]
nop, yet; still issue with lib dependencies

**Comment by victorsosa** [comment]
Trying to update to servlet 3.1.0, but getting a weird not found class
        <dependency>
            <groupId>javax.servlet</groupId>
            <artifactId>javax.servlet-api</artifactId>
            <version>3.1.0</version>
            <scope>provided</scope>
        </dependency>

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project struts2-core: Compilation failure: Compilation failure: 
[ERROR] /home/vns/workspace/struts/core/src/main/java/org/apache/struts2/views/jsp/ComponentTagSupport.java:[21,26] package javax.servlet.http does not exist
[ERROR] /home/vns/workspace/struts/core/src/main/java/org/apache/struts2/views/jsp/ComponentTagSupport.java:[22,26] package javax.servlet.http does not exist
[ERROR] /home/vns/workspace/struts/core/src/main/java/org/apache/struts2/components/Component.java:[40,26] package javax.servlet.http does not exist
[ERROR] /home/vns/workspace/struts/core/src/main/java/org/apache/struts2/components/Component.java:[41,26] package javax.servlet.http does not exist
[ERROR] /home/vns/workspace/struts/core/src/main/java/org/apache/struts2/views/jsp/ComponentTagSupport.java:[36,57] cannot find symbol
[ERROR]   symbol:   class HttpServletRequest
[ERROR]   location: class org.apache.struts2.views.jsp.ComponentTagSupport
[ERROR] /home/vns/workspace/struts/core/src/main/java/org/apache/struts2/views/jsp/ComponentTagSupport.java:[36,81] cannot find symbol
[ERROR]   symbol:   class HttpServletResponse

**Comment by victorsosa** [comment]
Ok, I fixed the servlet 3.1.0 dependency issue, now I got some class change issue in code

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project struts2-core: Compilation failure: Compilation failure: 
[ERROR] /home/vns/workspace/struts/core/src/main/java/org/apache/struts2/util/StrutsUtil.java:[271,12] org.apache.struts2.util.StrutsUtil.ServletOutputStreamWrapper is not abstract and does not override abstract method setWriteListener(javax.servlet.WriteListener) in javax.servlet.ServletOutputStream
[ERROR] /home/vns/workspace/struts/core/src/main/java/org/apache/struts2/util/URLBean.java:[73,53] incompatible types: java.util.Map<java.lang.String,java.lang.String[]> cannot be converted to java.util.Map<java.lang.String,java.lang.Object>
[ERROR] /home/vns/workspace/struts/core/src/main/java/org/apache/struts2/components/ServletUrlRenderer.java:[263,147] incompatible types: java.util.Map<java.lang.String,java.lang.String[]> cannot be converted to java.util.Map<java.lang.String,java.lang.Object>
[ERROR] /home/vns/workspace/struts/core/src/main/java/org/apache/struts2/components/Include.java:[290,18] org.apache.struts2.components.Include.PageOutputStream is not abstract and does not override abstract method setWriteListener(javax.servlet.WriteListener) in javax.servlet.ServletOutputStream

**Comment by victorsosa** [comment]
servlet 3.1.0 include some changes, working on it

**Review by sepe81 — CHANGES_REQUESTED** [review]
PR could be closed in favor of https://github.com/apache/struts/pull/552

**Pull request closed without merging**
