### PR TITLE
Fix freemaker error in checkbox.ftl of css_xhtml template 

### PR DESCRIPTION
**Pull request by tiv-source**
Fix freemaker error when set label position to left on a checkbox tag of a form (Missing brackets).

### CODE REVIEW

**Comment by lukaszlenart** [comment]
Please register issue in JIRA and link to this PR, this will allow us to collect changes when preparing a release notes. Thanks!

**Comment by tiv-source** [comment]
Fix for WW-4681 (Missing brackets in checkbox.ftl of css_xhtml template).

**Comment by tiv-source** [comment]
I have register this issue in JIRA but i don't know how to link correct hope this would do the trick.

**Comment by lukaszlenart** [comment]
That's ok

**Pull request merged**
